program 1
public class BasicExceptionHandling {
public static void main(String[] args) {
try {
int result = 10 / 0; 
} catch (ArithmeticException e) {
System.out.println("An arithmetic exception occurred: " + e.getMessage());
        }
    }
}


program 2
public class MultipleCatchBlocks {
public static void main(String[] args) {
try {
int[] numbers = {1, 2, 3};
System.out.println(numbers[5]); // This will throw an ArrayIndexOutOfBoundsException
} catch (ArrayIndexOutOfBoundsException e) {
System.out.println("An array index out of bounds exception occurred: " + e.getMessage());
} catch (Exception e) {
System.out.println("An unexpected exception occurred: " + e.getMessage());
        }
    }
}



program 3
Custom Exception Class
class CustomException extends Exception {
public CustomException(String message) {
super(message);
    }
}
public class CustomExceptionExample {
public static void main(String[] args) {
try {
throw new CustomException("This is a custom exception message.");
} catch (CustomException e) {
System.out.println("Custom Exception Caught: " + e.getMessage());
        }
    }
}

